namespace WinUI3App
{
	[default_interface]
	runtimeclass MyPage : Microsoft.UI.Xaml.Controls.Page
	{
		MyPage();
	}

	[default_interface]
	runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
	{
		MainPage();
	}

    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }
}
